### ISSUE TITLE
Ring Pointillist Student Yi Sang is missing from the selectable IDs list

### ISSUE THREAD

**Issue by LogicalExplosion** [LCTeamBuilder/LCTeamBuilder.github.io#1]
As stated in the title, Ring Yi Sang does not show up as an option when selecting Yi Sang identities, possibly due to forgetting to import and export it in `/src/Constants/Equipables.ts`.
![image](https://github.com/user-attachments/assets/f115f998-7d92-49ec-8359-ddac0c6963d8)

Thanks for making the site!

**Comment by SuenoImposible** [comment]
Fixed, thanks for reporting!
